print("Nhap vao mot so nguyen")
a=int(input())
print("Nhap vao mot so thuc")
x=float(input())
print("Nhap vao mot ki tu")
ch=input()
print("Nhap vao mot xau ki tu")
str=input()

print("Du lieu vua nhap vao")
print("So nguyen : ",a)
print("So thuc : ",x)
print("Ki tu : ",ch)
print("Xau ki tu : ",str)

